# Generated by Django 5.2.3 on 2025-07-22 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_notification'),
        ('paymentapp', '0004_order_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ecommerceapp.order'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
