# Generated by Django 5.2.3 on 2025-06-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_order_payment_order_status_alter_payment_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
