# Generated by Django 5.2.3 on 2025-07-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rescheduled_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('Repair', 'Repair'), ('Maintenance', 'Maintenance'), ('Inspection', 'Inspection'), ('Other', 'Other')], default='Repair', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
