# Generated by Django 5.2.3 on 2025-07-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0015_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('subheadline', models.CharField(blank=True, max_length=300)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='home_banners/')),
                ('call_to_action', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
