# Generated by Django 5.2.3 on 2026-05-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0021_add_jobcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='reorder_point',
            field=models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this level'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=10, help_text='Suggested quantity to reorder'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
